[general]
signup_mode = "nothing_required"
lmdb_backup_interval_s = 666
user_storage_quota_mb = 666

[drive]
pubky_listen_socket = "0.0.0.0:11111"
icann_listen_socket = "0.0.0.0:22222"
rate_limits = []

[admin]
listen_socket = "0.0.0.0:11111"
admin_password = "root"

[pkdns]
public_ip = "0.0.0.0"
icann_domain = "dummyhost"
user_keys_republisher_interval = 666
dht_relay_nodes = []

[logging]
level = "trace"
module_levels = [ ]
